### ISSUE TITLE
'go install' doesn't work

### ISSUE THREAD

**Issue by alekseyvit** [securego/gosec#1140]
### Summary 

go install github.com/securego/gosec/v2/cmd/gosec@latest

not works properly from 14 may 2024

### Steps to reproduce the behavior

after calling:
```
go install github.com/securego/gosec/v2/cmd/gosec@latest
```

### Operating system / Environment

Linux: ubuntu/debian

### Expected behavior

installed gosec 

### Actual behavior

//# github.com/securego/gosec/v2
/go/pkg/mod/github.com/securego/gosec/v2@v2.20.0/analyzer.go:378:36: undefined: ast.IsGenerated
/go/pkg/mod/github.com/securego/gosec/v2@v2.20.0/analyzer.go:461:10: undefined: ast.IsGenerated

soft is not installed

**Comment by ccojocar** [comment]
Which go version are you using? 

It seems to work fine with 1.22.3:

```
$go install github.com/securego/gosec/v2/cmd/gosec@latest
go: downloading github.com/securego/gosec/v2 v2.20.0
$ go version
go version go1.22.3 darwin/amd64
```

Note that only Go version `1.22.x` and `1.21.x` are supported.
