### PR TITLE
Assert that sample code compiles

### PR DESCRIPTION
**Pull request by cbandy**
This partially addresses #549. I fixed what seemed like typos to me, but there are still three failing specs that I'm not equipped to address:

1. `[Fail] gosec rules report correct errors for all samples [It] should detect pprof endpoint`

   The failing sample was introduced in 29341f6e. It seems to assert that importing `net/http/pprof` without an alias disables rule G108 when using `http.DefaultServeMux`. Is that the correct behavior?

   ```
   sample_1_0.go:8:2: "net/http/pprof" imported but not used
   ```

2. `[Fail] gosec rules report correct errors for all samples [It] should detect file path provided as taint input`

   The failing sample was introduced in f13b8bc6. It seems to assert that using `filepath.Rel` sanitizes path input, but that function returns an error. How should that error affect this sample?

   ```
   sample_8_0.go:11:37: too few arguments in call to filepath.Rel
   sample_8_0.go:11:16: cannot initialize 1 variables with 2 values
   ```

3. `[Fail] gosec rules report correct errors for all samples [It] should detect implicit aliasing in ForRange`

   The failing sample was introduced in ee3146e6. The `foo` function seems to be implemented for a `var vector []string`, while the rest of the sample is for a `var vector []*string`. What in this sample should change?

   ```
   sample_0_0.go:20:13: cannot use &item (value of type **string) as *string value in return statement
   sample_0_0.go:20:20: cannot use item (variable of type *string) as string value in return statement
   sample_0_0.go:22:1: missing return
   ```

### CODE REVIEW

**Review by ccojocar — APPROVED** [review]
Thanks for looking into this and for adding the check for compilation errors. I fixed these failing code samples. It is good to be merged now.
